//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umamido.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навигация на публикациите.
        /// </summary>
        public static string BlogNavigation {
            get {
                return ResourceManager.GetString("BlogNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следваща публикация.
        /// </summary>
        public static string BlogNext {
            get {
                return ResourceManager.GetString("BlogNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предишна публицация.
        /// </summary>
        public static string BlogPrev {
            get {
                return ResourceManager.GetString("BlogPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОЛИЧКА.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери адрес.
        /// </summary>
        public static string CheckAddress {
            get {
                return ResourceManager.GetString("CheckAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери от менюто.
        /// </summary>
        public static string ChooseFromMenu {
            get {
                return ResourceManager.GetString("ChooseFromMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете и поръчайте.
        /// </summary>
        public static string ChooseOrder {
            get {
                return ResourceManager.GetString("ChooseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СВЪРЖЕТЕ СЕ С НАС.
        /// </summary>
        public static string ConnectWithUs {
            get {
                return ResourceManager.GetString("ConnectWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОНТАКТИ.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Свържете се с нас, ако имате въпроси относно поръчки, доставки или друго, свързано с 25min.bg. Изберете най-удобния за Вас начин за връзка - по телефон или като попълните формата за конакт.&lt;/p&gt;&lt;p style=&quot;margin-bottom:0;&quot;&gt;Екипът ни е на Ваше разположение!&lt;/p&gt;.
        /// </summary>
        public static string ContactsBigText {
            get {
                return ResourceManager.GetString("ContactsBigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължаване с поръчката.
        /// </summary>
        public static string ContinueOrder {
            get {
                return ResourceManager.GetString("ContinueOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продуктът е добавен в количката. За да продължите с пазаруването, моля, въведете потребителско име и парола за вход в системата или, ако нямате регистрация, въведете адрес за доставка и направете проверка..
        /// </summary>
        public static string EnterCheckExplain {
            get {
                return ResourceManager.GetString("EnterCheckExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в профил / Провери адрес.
        /// </summary>
        public static string EnterCheckProfile {
            get {
                return ResourceManager.GetString("EnterCheckProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведи улица, номер.
        /// </summary>
        public static string EnterStreetNumber {
            get {
                return ResourceManager.GetString("EnterStreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият адрес все още не е в зоната за доставка. Можете да ни посетите на място на адрес .... . Моля, оставете email адрес, на който да ви уведомим за включването на вашия адрес в зоната на доставка..
        /// </summary>
        public static string FarAddress {
            get {
                return ResourceManager.GetString("FarAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравословна и питателна храна&lt;br&gt;с доставка до 25 минути..
        /// </summary>
        public static string HealthyFood {
            get {
                return ResourceManager.GetString("HealthyFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как да поръчаш.
        /// </summary>
        public static string HowToOrder {
            get {
                return ResourceManager.GetString("HowToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 min. | Fastest food delivery..
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидно потребителско име/и или парола.
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последно от блога.
        /// </summary>
        public static string LastBlogPosts {
            get {
                return ResourceManager.GetString("LastBlogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научавайте първи за нашите нови предложения.
        /// </summary>
        public static string LearnProposals {
            get {
                return ResourceManager.GetString("LearnProposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виж менюто.
        /// </summary>
        public static string LookMenu {
            get {
                return ResourceManager.GetString("LookMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лв..
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съобщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МОЯТ ПРОФИЛ.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчай.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОРЪЧКА И ДОСТАВКА.
        /// </summary>
        public static string OrderAndDelivery {
            get {
                return ResourceManager.GetString("OrderAndDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчка и доставка | 25 min..
        /// </summary>
        public static string OrderPaymentTitle {
            get {
                return ResourceManager.GetString("OrderPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плати с карта или кеш.
        /// </summary>
        public static string PayWithCardOrCache {
            get {
                return ResourceManager.GetString("PayWithCardOrCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е в зоната за доставка. Моля, продължете с пазаруването..
        /// </summary>
        public static string PleaseContinue {
            get {
                return ResourceManager.GetString("PleaseContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо продукти.
        /// </summary>
        public static string ProductsTotal {
            get {
                return ResourceManager.GetString("ProductsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторанти.
        /// </summary>
        public static string Restaurants {
            get {
                return ResourceManager.GetString("Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресторанти | 25 min..
        /// </summary>
        public static string RestaurantsTitle {
            get {
                return ResourceManager.GetString("RestaurantsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виж карта.
        /// </summary>
        public static string SeeMap {
            get {
                return ResourceManager.GetString("SeeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виж повече.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сподели.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подобни продукти.
        /// </summary>
        public static string SimilarProducts {
            get {
                return ResourceManager.GetString("SimilarProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запишете се за нашия бюлетин.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записване.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБЩИ УСЛОВИЯ.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очаквай до &lt;span&gt;25&lt;/span&gt; минути.
        /// </summary>
        public static string WaitMinutes {
            get {
                return ResourceManager.GetString("WaitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всеки ден в часовете между &lt;strong&gt;10.00 ч. - 22.00 ч.&lt;/strong&gt;.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работно време, в което се изпълняват поръчки и доставки.
        /// </summary>
        public static string WorkTimeTitle {
            get {
                return ResourceManager.GetString("WorkTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият адрес.
        /// </summary>
        public static string YourAddress {
            get {
                return ResourceManager.GetString("YourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашето име.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
