//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddress
    {
        public int ClientAddressId { get; set; }
        public int AddressNum { get; set; }
        public int ClientId { get; set; }
        public string FirstName { get; set; }
        public string Faimly { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
