//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientAddress = new HashSet<ClientAddress>();
            this.Req = new HashSet<Req>();
        }
    
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Familyname { get; set; }
        public string eMail { get; set; }
        public string CompanyName { get; set; }
        public string EIK { get; set; }
        public string VAT { get; set; }
        public string PersonName { get; set; }
        public string CompanyAddress { get; set; }
        public string PK { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAddress> ClientAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Req> Req { get; set; }
    }
}
