//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.Good1 = new HashSet<Good>();
            this.Good11 = new HashSet<Good>();
            this.Good12 = new HashSet<Good>();
            this.GoodDesc = new HashSet<GoodDesc>();
            this.GoodTitle = new HashSet<GoodTitle>();
            this.Req2Good = new HashSet<Req2Good>();
        }
    
        public int GoodId { get; set; }
        public int RestaurantId { get; set; }
        public int ImageId { get; set; }
        public decimal Price { get; set; }
        public int CookMinutes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Similar1Id { get; set; }
        public Nullable<int> Similar2Id { get; set; }
        public Nullable<int> Similar3Id { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Good> Good1 { get; set; }
        public virtual Good Good2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Good> Good11 { get; set; }
        public virtual Good Good3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Good> Good12 { get; set; }
        public virtual Good Good4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodDesc> GoodDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodTitle> GoodTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Req2Good> Req2Good { get; set; }
    }
}
