//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public System.DateTime OnDate { get; set; }
        public string FromName { get; set; }
        public string EMail { get; set; }
        public string Subject { get; set; }
        public string MessageText { get; set; }
    }
}
