//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Req()
        {
            this.Req2Good = new HashSet<Req2Good>();
            this.Inv = new HashSet<Inv>();
        }
    
        public int ReqId { get; set; }
        public int PaymentTypeId { get; set; }
        public int ClientId { get; set; }
        public string Address { get; set; }
        public bool Invoice { get; set; }
        public string Address2 { get; set; }
        public string Note { get; set; }
        public System.DateTime OnDate { get; set; }
        public string Receiver { get; set; }
        public string LatLong { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Req2Good> Req2Good { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv> Inv { get; set; }
    }
}
