//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req2Status
    {
        public int Req2StatusId { get; set; }
        public int ReqId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime OnDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Note { get; set; }
    }
}
