//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req2Good
    {
        public int Req2GoodId { get; set; }
        public int ReqId { get; set; }
        public int GoodId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Req Req { get; set; }
    }
}
