//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderDesc
    {
        public int SliderDescId { get; set; }
        public int SliderId { get; set; }
        public int LangId { get; set; }
        public string Text { get; set; }
    
        public virtual Lang Lang { get; set; }
        public virtual Slider Slider { get; set; }
    }
}
