//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umamido.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReq
    {
        public int ReqId { get; set; }
        public System.DateTime OnDate { get; set; }
        public int StatusId { get; set; }
        public int ClientId { get; set; }
    }
}
